services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=gena
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fitin
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: sh -c "python3 manage.py migrate && 
                    gunicorn --env DJANGO_SETTINGS_MODULE=fitin.settings --bind 0.0.0.0:8000 fitin.wsgi"
    environment:
      - DB_PASSWORD=123456
      - DB_USER=gena
      - DB_DATABASE=fitin
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
