# Generated by Django 4.1.7 on 2023-05-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(blank=True, verbose_name='Библиографическое описание')),
                ('list_id', models.CharField(default='', max_length=300)),
                ('pub_date', models.CharField(default='', max_length=100)),
                ('explanations', models.CharField(blank=True, max_length=300, verbose_name='Пояснения к заглавию, жанру и т.п.')),
                ('content', models.CharField(blank=True, max_length=300, verbose_name='Вид содержания')),
                ('access_means', models.CharField(blank=True, max_length=300, verbose_name='Средство доступа')),
                ('surname', models.CharField(default='', max_length=300, verbose_name='Фамилия автора')),
                ('initials', models.CharField(default='', max_length=300, verbose_name='Инициалы автора')),
                ('second_surname', models.CharField(blank=True, max_length=300, verbose_name='Фамилия второго автора')),
                ('second_initials', models.CharField(blank=True, max_length=300, verbose_name='Инициалы второго автора')),
                ('second_surname_2', models.CharField(blank=True, max_length=300, verbose_name='Фамилия второго автора')),
                ('second_initials_2', models.CharField(blank=True, max_length=300, verbose_name='Инициалы второго автора')),
                ('third_surname', models.CharField(blank=True, max_length=300, verbose_name='Фамилия третьего автора')),
                ('third_initials', models.CharField(blank=True, max_length=300, verbose_name='Инициалы третьего автора')),
                ('second_surname_3', models.CharField(blank=True, max_length=300, verbose_name='Фамилия второго автора')),
                ('second_initials_3', models.CharField(blank=True, max_length=300, verbose_name='Инициалы второго автора')),
                ('third_surname_2', models.CharField(blank=True, max_length=300, verbose_name='Фамилия третьего автора')),
                ('third_initials_2', models.CharField(blank=True, max_length=300, verbose_name='Инициалы третьего автора')),
                ('fourth_surname', models.CharField(blank=True, max_length=300, verbose_name='Фамилия четвертого автора')),
                ('fourth_initials', models.CharField(blank=True, max_length=300, verbose_name='Инициалы четвертого автора')),
                ('second_surname_4', models.CharField(blank=True, max_length=300, verbose_name='Фамилия второго автора')),
                ('second_initials_4', models.CharField(blank=True, max_length=300, verbose_name='Инициалы второго автора')),
                ('third_surname_3', models.CharField(blank=True, max_length=300, verbose_name='Фамилия третьего автора')),
                ('third_initials_3', models.CharField(blank=True, max_length=300, verbose_name='Инициалы третьего автора')),
                ('edit_info', models.CharField(blank=True, max_length=300, verbose_name='Сведения об издании (если указаны)')),
                ('parallel', models.CharField(blank=True, max_length=300, verbose_name='Параллельное заглавие')),
                ('type_doc', models.CharField(blank=True, max_length=300, verbose_name='Сведения о заглавии')),
                ('responsibility', models.CharField(blank=True, max_length=300, verbose_name='Сведения об ответственности')),
                ('par_edit_info', models.CharField(blank=True, max_length=300, verbose_name='Пар. сведения об издании')),
                ('liability', models.CharField(blank=True, max_length=300, verbose_name='Свед. об отв-ти, относ. к изданию')),
                ('place_of_distribution', models.CharField(blank=True, max_length=300, verbose_name='Место распространения')),
                ('organization_of_distribution', models.CharField(blank=True, max_length=300, verbose_name='Организация распространения')),
                ('distribution_date', models.CharField(blank=True, max_length=300, verbose_name='Дата распространения')),
                ('manufacture', models.CharField(blank=True, max_length=300, verbose_name='Сведения об изготовлении')),
                ('unnumbered_pages', models.CharField(blank=True, max_length=300, verbose_name='Ненумерованные страницы')),
                ('illustrations', models.CharField(blank=True, max_length=300, verbose_name='Ненумерованные листы, столбцы')),
                ('accompanying', models.CharField(blank=True, max_length=300, verbose_name='Сопроводительный материал')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='Примечания')),
                ('general_notes', models.CharField(blank=True, max_length=300, verbose_name='Примечания общего характера')),
                ('additional_information', models.CharField(blank=True, max_length=300, verbose_name='Доп. свед-я идентификатора ресурса')),
                ('availability', models.CharField(blank=True, max_length=300, verbose_name='Условия доступности')),
                ('content_type', models.CharField(blank=True, max_length=300, verbose_name='Характеристика содержания')),
                ('main_title', models.CharField(blank=True, max_length=300, verbose_name='Основное заглавие серии')),
                ('parallel_series_title', models.CharField(blank=True, max_length=300, verbose_name='Параллельное заглавие серии')),
                ('series_title_information', models.CharField(blank=True, max_length=300, verbose_name='Свед-я, относ. к заглавию серии')),
                ('responsibility_info', models.CharField(blank=True, max_length=300, verbose_name='Свед-я об отв-ти, относ. к серии')),
                ('number', models.CharField(blank=True, max_length=300, verbose_name='Междунар. станд. номер серии')),
                ('serial_number', models.CharField(blank=True, max_length=300, verbose_name='Номер выпуска серии')),
                ('sub_main_title', models.CharField(blank=True, max_length=300, verbose_name='Основное заглавие подсерии')),
                ('sub_parallel_series_title', models.CharField(blank=True, max_length=300, verbose_name='Пар. заглавие подсерии')),
                ('sub_series_title_information', models.CharField(blank=True, max_length=300, verbose_name='Свед-я, относ. к заглавию подсерии')),
                ('sub_responsibility_info', models.CharField(blank=True, max_length=300, verbose_name='Свед-я об отв-ти, относ. к подсерии')),
                ('sub_number', models.CharField(blank=True, max_length=300, verbose_name='Междунар. станд. номер подсерии')),
                ('sub_serial_number', models.CharField(blank=True, max_length=300, verbose_name='Номер выпуска подсерии')),
                ('title', models.CharField(max_length=300, verbose_name='Название книги')),
                ('place', models.CharField(max_length=300, verbose_name='Место издания')),
                ('publishing', models.CharField(max_length=300, verbose_name='Издательство')),
                ('year', models.CharField(max_length=300, verbose_name='Год издания книги')),
                ('pages', models.CharField(max_length=300, verbose_name='Количество страниц')),
                ('isbn', models.CharField(blank=True, max_length=300, verbose_name='ISBN (если указан)')),
                ('fingerprint', models.CharField(blank=True, max_length=300, verbose_name='Фингерпринт (для старопеч. изд.)')),
                ('size', models.CharField(blank=True, max_length=300, verbose_name='Размер издания (в см)')),
                ('physical_characteristics', models.CharField(blank=True, max_length=300, verbose_name='Физические характеристики')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
