# Generated by Django 3.1.5 on 2021-04-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basketmodel_productfavoritemodel_productmodel_reviewmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
